global:
    scrape_interval: 15s
    scrape_timeout: 10s
scrape_configs:
    - job_name: "prometheus"
      static_configs:
          - targets: ["192.168.1.11:9090"]
    - job_name: "loki"
      static_configs:
          - targets: ["192.168.1.11:3100"]
    - job_name: "serving_server"
      static_configs:
          - targets: ["192.168.1.11:8000"]
